### ISSUE TITLE
Error when running in codespace

### ISSUE THREAD

**Issue by hairy-tortoise** [Rahullkumr/Flutter-Codespaces#1]
shiny-train-jgpw6467xv9hpwq4-3000.app.github.dev/:1  Access to internal resource at 'https://github.dev/pf-signin?id=quick-ocean-06grggj&cluster=euw&name=shiny-train-jgpw6467xv9hpwq4&port=3000&pb=https%3A%2F%2Fshiny-train-jgpw6467xv9hpwq4-3000.app.github.dev%2Fauth%2Fpostback%2Ftunnel%3Frd%3D%252Fmanifest.json%26tunnel%3D1' (redirected from 'https://shiny-train-jgpw6467xv9hpwq4-3000.app.github.dev/manifest.json') from origin 'https://shiny-train-jgpw6467xv9hpwq4-3000.app.github.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by Rahullkumr** [comment]
Let me check and I'll let you know.

By that time, learn about [ProjectIDX ](https://idx.dev/) and join their waitlist (if not joined yet).

ProjectIDX is the best choice for Flutter development on the cloud.

**Comment by Rahullkumr** [comment]
I just checked, It's working fine.

Please read the documentation (README file) properly.

**In the ports view (the PORTS tab in the terminal), port 3000 should be listed there already. Right click on it, and, under "Port Visibility", select "Public". This is important so the app can access services on your client from other server ports without getting blocked due to CORS.**

If you still have doubt, ask it.
